import type { Metadata } from "next";
import { Alegreya, Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NavBar from "../components/Navigation/NavBar";
import localFont from 'next/font/local';
import Footer from "../components/Footer/Footer";
import Wave from 'react-wavify'
import LayoutClient from "./LayoutClient";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const alegreya = Alegreya({
  variable : "--font-alegreya"
})

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Bat Cave Cafe",
  description: "Generated by create next app yezzoir",
};

const InterFont = localFont({
  src: '../../public/fonts/Inter-VariableFont_opsz,wght.ttf',
  variable: '--font-inter', // optional, for CSS variable
})

const Cinzel = localFont({
  src : "../../public/fonts/CinzelDecorative-Bold.ttf",
  variable : '--font-Cinzel'
})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        
      </head>
      
      <body className={`${geistSans.variable} ${geistMono.variable} ${InterFont.variable} ${Cinzel.variable} antialiased ${alegreya.variable} `}  style={{
        // height : "1339px"
        background : "#967259"
      }}>
        <svg style={{ position: "absolute", width: 0, height: 0 }}>
          <defs>
            <filter id="goo">
              <feGaussianBlur in="SourceGraphic" result="blur" stdDeviation="10" />
              <feColorMatrix in="blur" mode="matrix" values="1 0 0 0 0  0 1 0 0 0  0 0 1 0 0  0 0 0 18 -7" result="goo" />
              <feGaussianBlur in="goo" stdDeviation="1" result="shadow" />
              <feColorMatrix in="shadow" mode="matrix" values="0 0 0 0 0  0 0 0 0 0  0 0 0 0 0  0 0 0 1 -0.2" result="shadow" />
              <feOffset in="shadow" dx="1" dy="1" result="shadow" />
              <feComposite in2="shadow" in="goo" result="goo" />
              <feComposite in2="goo" in="SourceGraphic" result="mix" />
          </filter>
          <filter id="goo">
              <feGaussianBlur in="SourceGraphic" result="blur" stdDeviation="10" />
              <feColorMatrix in="blur" mode="matrix" values="1 0 0 0 0  0 1 0 0 0  0 0 1 0 0  0 0 0 18 -7" result="goo" />
              <feComposite in2="goo" in="SourceGraphic" result="mix" />
            </filter>
          </defs>
        </svg>

        {/* wrapped it in a component to conditionally generate the navbar without affecting ssr */}
        <LayoutClient>
          <NavBar/>
          {/* <Wave
            // fill="var(--color-coffee-medium)"
            fill="url(#gradient)"
            className="absolute top-0 z-1" 
            style={{ transform : "scaleY(-1)", height : "180px" }}
            paused={false}
            options={{
              height: 0,
              amplitude: 20,
              speed: 0.25,
              points: 3
            }}>
            <defs>
              <linearGradient id="gradient" gradientTransform="rotate(90)">
                <stop offset="10%"  stopColor="var(--color-coffee-medium)" />
                <stop offset="90%" stopColor="var(--color-coffee-dark)" />
              </linearGradient>
            </defs>
          </Wave> */}
        </LayoutClient>

        {children}
      <Footer />
      </body>
    </html>
  );
}
// bg-linear-to-r from-amber-600 to-yellow-400 peak ahh button design
