import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NavBar from "../components/Navigation/NavBar";
import localFont from 'next/font/local';
import video from ''


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Bat Cave Cafe",
  description: "Generated by create next app yezzoir",
};


const InterFont = localFont({
  src: '../../public/fonts/Inter-VariableFont_opsz,wght.ttf',
  variable: '--font-inter', // optional, for CSS variable
})


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} ${InterFont.className} antialiased`} style={{
        height : "1000px"
      }}>
        <NavBar/>
      {/* Video */}
      <video className="-z-1" src="/videos/backgroundVideo.mp4" autoPlay loop muted
      style={{
        minWidth : "100%",
        minHeight : "100%",
        filter : "blur(8px)"
      }}/>
        {children}
      </body>
    </html>
  );
}
