import type { Metadata } from "next";
import { Alegreya, Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NavBar from "../components/Navigation/NavBar";
import localFont from 'next/font/local';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const alegreya = Alegreya({
  variable : "--font-alegreya"
})

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Bat Cave Cafe",
  description: "Generated by create next app yezzoir",
};

const InterFont = localFont({
  src: '../../public/fonts/Inter-VariableFont_opsz,wght.ttf',
  variable: '--font-inter', // optional, for CSS variable
})

const Cinzel = localFont({
  src : "../../public/fonts/CinzelDecorative-Bold.ttf",
  variable : '--font-Cinzel'
})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable} ${InterFont.variable} ${Cinzel.variable} antialiased ${alegreya.variable} `}  style={{
        // height : "1339px"
      }}>
      <NavBar/>
      {/* Video */}
      <video 
        className="absolute top-0 left-0 w-full h-[1400px] object-cover -z-10" 
        src="/videos/backgroundVideo.mp4" 
        autoPlay 
        loop 
        muted
        style={{
          filter: "blur(8px)"
        }}
      />
        {children}
      </body>
    </html>
  );
}
